cnfPrySGCS/cnfPrySGCS/Areas/cnfMantenimiento/Controllers/cnfClsMetodologiaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using cnfPrySGCS.Models;

// 

namespace cnfPrySGCS.Areas.cnfMantenimiento.Controllers
{
    public class cnfClsMetodologiaController : Controller
    {
        private cnfMTDpMetodologia PobjMetodologia = new cnfMTDpMetodologia();
        // GET: cnfClsMetodologia
        public ActionResult cnfFrmMetodologiaVista(int id = 0)
        {
            try
            {
                if (ViewBag.GblnMensaje == null)
                {
                    ViewBag.GblnMensaje = Convert.ToBoolean(Session["GblnMensaje"].ToString());
                    ViewBag.GstrMensajeRespuesta = Convert.ToString(Session["GstrMensajeRespuesta"].ToString());
                }
            }
            catch
            {

            }
            
            ViewBag.GobjListarMetodologia = mtdCargarDatos();
            Session["GblnMensaje"] = false;
            Session["GstrMensajeRespuesta"] = "";
            return View(id == 0 ? new cnfMTDpMetodologia()
                : mtdBuscar(id));
        }

        public object mtdBuscar(int LintCodigo)
        {
            cnfMTDpMetodologia LobjMetodologia = new cnfMTDpMetodologia();
            return PobjMetodologia.mtdBuscar(LintCodigo);
        }

        public object mtdCargarDatos()
        {
            return PobjMetodologia.mtdCargarDatos();
        }

        public ActionResult mtdGuardar(cnfMTDpMetodologia PobjMetodologiaModelo)
        {
            string LstrMensajeRespuesta = "";

            if (ModelState.IsValid)
            { 
                if(PobjMetodologiaModelo.MTDcodigo == 0)
                {
                    LstrMensajeRespuesta = PobjMetodologiaModelo.mtdGuardar(PobjMetodologiaModelo);
                    mtdRespuestaMensaje(LstrMensajeRespuesta);
                }
                else
                {
                    LstrMensajeRespuesta = mtdModificar(PobjMetodologiaModelo);
                    mtdRespuestaMensaje(LstrMensajeRespuesta);
                }
            }
            return Redirect("~/cnfMantenimiento/cnfClsMetodologia/cnfFrmMetodologiaVista");
        }

        public string mtdModificar(cnfMTDpMetodologia PobjMetodologiaModelo)
        {
            string LstrMensajeRespuesta = "";
            LstrMensajeRespuesta = PobjMetodologiaModelo.mtdModificar(PobjMetodologiaModelo);
            return LstrMensajeRespuesta;
        }

        public void mtdRespuestaMensaje(string LstrMensajeRespuesta)
        {
            if(LstrMensajeRespuesta.Equals("Correcto"))
            {
                Session["GblnMensaje"] = true;
                Session["GstrMensajeRespuesta"] = "La Operación se Realizó Correctamente";
            }
            else
            {
                Session["GblnMensaje"] = true;
                Session["GstrMensajeRespuesta"] = "Ocurrió un Fallo en la Operación";
            }
        }
    }
}

cnfPrySGCS/cnfPrySGCS/Areas/cnfMantenimiento/Views/cnfClsMetodologia/cnfFrmMetodologiaVista.cshtml
@model cnfPrySGCS.Models.cnfMTDpMetodologia
@{
    List<cnfPrySGCS.Models.cnfMTDpMetodologia> GobjListarMetodologia = ViewBag.GobjListarMetodologia;
    bool LblnMensaje = false;
    try
    {
        LblnMensaje = ViewBag.GblnMensaje;
    }
    catch
    {

    }
}

@try
{
    if (LblnMensaje)
    {
        string LstrMensaje = ViewBag.GstrMensajeRespuesta;

        if (LstrMensaje.Equals("La Operación se Realizó Correctamente"))
        {
            <script>
                    alert('La Operación se Realizó Correctamente');
            </script>
        }
        else
        {
            <script>
                    alert('Ocurrió un Fallo en la Operación');
            </script>
        }
    }
}
catch
{

}

<script type="text/javascript">
(function(document) {
  'use strict';

  var LightTableFilter = (function(Arr) {

    var _input;

    function _onInputEvent(e) {
      _input = e.target;
      var tables = document.getElementsByClassName(_input.getAttribute('data-table'));
      Arr.forEach.call(tables, function(table) {
        Arr.forEach.call(table.tBodies, function(tbody) {
          Arr.forEach.call(tbody.rows, _filter);
        });
      });
    }

    function _filter(row) {
      var text = row.textContent.toLowerCase(), val = _input.value.toLowerCase();
      row.style.display = text.indexOf(val) === -1 ? 'none' : 'table-row';
    }

    return {
      init: function() {
        var inputs = document.getElementsByClassName('txtBuscar');
        Arr.forEach.call(inputs, function(input) {
          input.oninput = _onInputEvent;
        });
      }
    };
  })(Array.prototype);

  document.addEventListener('readystatechange', function() {
    if (document.readyState === 'complete') {
      LightTableFilter.init();
    }
  });

})(document);
</script>

<div class="row">
    <div class="col-md-12">
        <div class="block-web">
            <div class="header">
                <div class="actions"> <a class="minimize" href="~/Content/ultimo_admin/admin/#"><i class="fa fa-chevron-down"></i></a></div>
                <a href="~/cnfClsMetodologia/cnfFrmMetodologiaVista"><h3 class="content-header">Metodologia</h3></a>
            </div>
            <div class="porlets-content">
                @using (Html.BeginForm("mtdGuardar", "cnfClsMetodologia", FormMethod.Post, new { id = "FrmMetodologia", @name = "FrmMetodologia", @class = "form-horizontal row-border" }))
                {
                    @Html.HiddenFor(x => x.MTDcodigo)

                    <div class="form-group">
                        <label name="lblCodigo" class="col-sm-3 control-label">Codigo</label>
                        <div class="col-sm-9">
                            @Html.TextBoxFor(x => x.MTDcodigo, new { @class = "form-control", @disabled = true })
                        </div>
                    </div><!--/form-group-->


                    <div class="form-group">
                        <label name="lblNombreMetodologia" class="col-sm-3 control-label">Nombre de Metodologia</label>
                        <div class="col-sm-9">
                            @Html.TextBoxFor(x => x.MTDnombre, new { @class = "form-control", @required = "true", @pattern = "[A-Za-z ]+" })
                        </div>
                    </div><!--/form-group-->


                    <div class="form-group">
                        <label name="lblEstado" class="col-sm-3 control-label">Estado</label>
                        <div class="col-sm-9">
                            <select class="form-control" id="source" name="MTDestado">
                                @try
                                {
                                    if (Model.MTDestado.Equals(""))
                                    {
                                        <optgroup label="Estado">
                                            <option value="Activo">Activo</option>
                                            <option value="Inactivo">Inactivo</option>
                                        </optgroup>
                                    }
                                    else if (Model.MTDestado.Equals("Activo"))
                                    {
                                        <optgroup label="Estado">
                                            <option value="Activo" selected>Activo</option>
                                            <option value="Inactivo">Inactivo</option>
                                        </optgroup>
                                    }
                                    else if (Model.MTDestado.Equals("Inactivo"))
                                    {
                                        <optgroup label="Estado">
                                            <option value="Activo">Activo</option>
                                            <option value="Inactivo" selected>Inactivo</option>
                                        </optgroup>
                                    }
                                }
                                catch
                                {
                                    <optgroup label="Estado">
                                        <option value="Activo">Activo</option>
                                        <option value="Inactivo">Inactivo</option>
                                    </optgroup>
                                }

                            </select>
                        </div><!--/col-sm-9-->
                    </div><!--/form-group-->


                    <div class="form-group">
                        <label name="lblFechaRegistro" class="col-sm-3 control-label">Fecha Registro</label>
                        <div class="col-sm-9">
                            @try
                            {
                                DateTime LdttFechaActual = DateTime.Now;
                                string LstrFechaActual = LdttFechaActual.ToString("d");
                                <input type="text" class="form-control" disabled="" name="fecha_Registro" value="@LstrFechaActual" />
                                    <input type="hidden" class="form-control" name="MTDfecha_Registro" value="@LstrFechaActual" />
                            }
                            catch
                            {

                            }
                        </div>
                    </div><!--/form-group-->

                    <div class="text-right">
                        <button type="submit" class="btn btn-success">Guardar</button>
                    </div>

                }

                <div class="row">
                    <div class="col-md-12">
                        <div class="block-web">
                            <div class="header">
                                <div class="actions">
                                    <a class="minimize" href="#"><i class="fa fa-chevron-down"></i></a>
                                </div>
                            </div>
                            <div class="porlets-content">
                                <div class="adv-table editable-table ">
                                    <div class="margin-top-10"></div>
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="dataTables_length" id="editable-sample_length">
                                            </div>
                                        </div><div class="col-lg-12"><label>Buscar: <input class="txtBuscar form-control" aria-controls="editable-sample" data-table="order-table" type="search" placeholder="Buscar por Nombre..." /></label></div>
                                    </div>
                                    <table class="table table-striped table-hover table-bordered order-table" id="editable-sample">
                                        <thead>
                                            <tr>
                                                <th>Codigo</th>
                                                <th>Metodologia</th>
                                                <th>Fecha de Registro</th>
                                                <th>Estado</th>
                                                <th>Acción</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @try
                                            {
                                                foreach (var LobjRegistro in GobjListarMetodologia)
                                                {
                                                    <tr class="">
                                                        <td>@LobjRegistro.MTDcodigo</td>
                                                        <td>@LobjRegistro.MTDnombre</td>
                                                        @try
                                                        {
                                                            string LstrFechaActual = Convert.ToDateTime(LobjRegistro.MTDfecha_Registro).ToString("d");
                                                            <td>@LstrFechaActual</td>
                                                        }
                                                        catch
                                                        {

                                                        }

                                                        <td>@LobjRegistro.MTDestado</td>
                                                        <td><a class="btn btn-warning" href="~/cnfMantenimiento/cnfClsMetodologia/cnfFrmMetodologiaVista/@LobjRegistro.MTDcodigo">Modificar</a></td>
                                                    </tr>
                                                }
                                            }
                                            catch
                                            {

                                            }
                                        </tbody>
                                    </table>
                                </div>

                            </div><!--/porlets-content-->
                        </div><!--/block-web-->
                    </div><!--/col-md-12-->
                </div><!--/row-->
            </div>
        </div>
    </div>
</div>