cnfPrySGCS/cnfPrySGCS/Areas/cnfProyecto/Controllers/cnfClsEntregaController.cs
using cnfPrySGCS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace cnfPrySGCS.Areas.cnfProyecto.Controllers
{
    public class cnfClsEntregaController : Controller
    {
        // GET: cnfMantenimiento/cnfClsEntrega


        cnfEMEpEntregableMiembroEntregable PobjEntrega = new cnfEMEpEntregableMiembroEntregable();
        // GET:  cnfEEMpEntregaEntregableMiembro PobjEntregable

        public ActionResult cnfFrmEntrega(int id = 0)
        {
            return View();
            //try
            //{
            //    if (ViewBag.GblnMensaje == null)
            //    {
            //        ViewBag.GblnMensaje = Convert.ToBoolean(Session["GblnMensaje"].ToString());
            //        ViewBag.GstrMensajeRespuesta = Convert.ToString(Session["GstrMensajeRespuesta"].ToString());
            //    }
            //}
            //catch
            //{

            //}

            //ViewBag.GobjListarEntregable = mtdCargarDatosPrincipal();
            //ViewBag.GobjListarMetodologia = mtdCargarComboMetodologia();
            //Session["GblnMensaje"] = false;
            //Session["GstrMensajeRespuesta"] = "";
            //Session["GintMNTcodigo"] = id;
            //return View(id == 0 ? new cnfMNTpMetodologiaEntregable.cnfMNTpMetodologiaEntregables()
            //    : mtdBuscar(id));
        }

        public ActionResult cnfFrmEntregaVista(int id = 0)
        {


            try
            {
                if (ViewBag.GblnMensaje == null)
                {
                    ViewBag.GblnMensaje = Convert.ToBoolean(Session["GblnMensaje"].ToString());
                    ViewBag.GstrMensajeRespuesta = Convert.ToString(Session["GstrMensajeRespuesta"].ToString());
                }
            }
            catch
            {

            }


            ViewBag.GobjListarEntrega = mtdCargarDatosPrincipal();
            ViewBag.GobJListarProyecto = mtdCargarComboProyecto();
            Session["GblnMensaje"] = false;
            Session["GstrMensajeRespuesta"] = "";

            return View(id == 0 ? new cnfEMEpEntregableMiembroEntregable()
          : mtdBuscar(id));


        }

        public object mtdCargarComboProyecto()
        {
            cnfPRYpProyecto LobjProyecto = new cnfPRYpProyecto();
            return LobjProyecto.mtdCargarComboProyecto();
        }

        public object mtdCargarDatosPrincipal()
        {
            return PobjEntrega.mtdCargarDatosPrincipal();
        }
        public object mtdBuscar(int LintCodigo)
        {

            cnfEMEpEntregableMiembroEntregable LobjEntrega = new cnfEMEpEntregableMiembroEntregable();
            return PobjEntrega.mtdBuscar(LintCodigo);
        }


        public ActionResult cnfFrmEntregaEvaluador(int id = 0)
        {
            return View();
            //try
            //{
            //    if (ViewBag.GblnMensaje == null)
            //    {
            //        ViewBag.GblnMensaje = Convert.ToBoolean(Session["GblnMensaje"].ToString());
            //        ViewBag.GstrMensajeRespuesta = Convert.ToString(Session["GstrMensajeRespuesta"].ToString());
            //    }
            //}
            //catch
            //{

            //}

            //ViewBag.GobjListarEntregable = mtdCargarDatosPrincipal();
            //ViewBag.GobjListarMetodologia = mtdCargarComboMetodologia();
            //Session["GblnMensaje"] = false;
            //Session["GstrMensajeRespuesta"] = "";
            //Session["GintMNTcodigo"] = id;
            //return View(id == 0 ? new cnfMNTpMetodologiaEntregable.cnfMNTpMetodologiaEntregables()
            //    : mtdBuscar(id));
        }


        public ActionResult cnfFrmEntregaResponsable(int id = 0)
        {
            return View();
            //try
            //{
            //    if (ViewBag.GblnMensaje == null)
            //    {
            //        ViewBag.GblnMensaje = Convert.ToBoolean(Session["GblnMensaje"].ToString());
            //        ViewBag.GstrMensajeRespuesta = Convert.ToString(Session["GstrMensajeRespuesta"].ToString());
            //    }
            //}
            //catch
            //{

            //}

            //ViewBag.GobjListarEntregable = mtdCargarDatosPrincipal();
            //ViewBag.GobjListarMetodologia = mtdCargarComboMetodologia();
            //Session["GblnMensaje"] = false;
            //Session["GstrMensajeRespuesta"] = "";
            //Session["GintMNTcodigo"] = id;
            //return View(id == 0 ? new cnfMNTpMetodologiaEntregable.cnfMNTpMetodologiaEntregables()C:\Users\duard\Source\Repos\SGCS3\Sistema SGCS\cnfPrySGCS\cnfPrySGCS\Areas\cnfProyecto\Controllers\cnfClsEntregaEntregableController.cs
            //    : mtdBuscar(id));
        }

        //public object mtdCargarComboMetodologia()
        //{
        //    cnfMNTpMetodologiaEntregable LobjEntregable = new cnfMNTpMetodologiaEntregable();
        //    return LobjEntregable.mtdCargarComboMetodologia();
        //}

        //[HttpPost]
        //public ActionResult mtdCargarComboFase(int MTDcodigo)
        //{
        //    cnfMNTpMetodologiaEntregable LobjEntregable = new cnfMNTpMetodologiaEntregable();
        //    ViewBag.GobjListarFase = LobjEntregable.mtdCargarComboFase(MTDcodigo);
        //    ViewBag.GobjListarMetodologia = mtdCargarComboMetodologia();
        //    ViewBag.GobjListarEntregable = mtdCargarDatosPrincipal();
        //    ViewBag.GintMetodologiaSeleccionada = MTDcodigo;
        //    return View("cnfFrmEntregableVista", Convert.ToInt32(Session["GintMNTcodigo"].ToString()) == 0 ? new cnfMNTpMetodologiaEntregable.cnfMNTpMetodologiaEntregables()
        //        : mtdBuscar(Convert.ToInt32(Session["GintMNTcodigo"].ToString())));
        //}

        //public object mtdBuscar(int LintCodigo)           
        //{
        //    cnfMNTpMetodologiaEntregable LobjEntregable = new cnfMNTpMetodologiaEntregable();
        //    cnfMNTpMetodologiaEntregable.cnfMNTpMetodologiaEntregables LobjEntregables = LobjEntregable.mtdBuscar(LintCodigo);
        //    ViewBag.GobjListarFase = LobjEntregable.mtdCargarComboFase(LobjEntregables.MTDcodigo);
        //    return LobjEntregable.mtdBuscar(LintCodigo);
        //}

        //public object mtdCargarDatosPrincipal()
        //{
        //    return PobjEntregable.mtdCargarDatosPrincipal();
        //}

        //public ActionResult mtdGuardarPrincipal(cnfMNTpMetodologiaEntregable.cnfMNTpMetodologiaEntregables LobjEntregableModelo)
        //{
        //    string LstrMensajeRespuesta = "";

        //    cnfMNTpMetodologiaEntregable LobjEntregable = new cnfMNTpMetodologiaEntregable();
        //    LobjEntregable.MNTcodigo = LobjEntregableModelo.MNTcodigo;
        //    LobjEntregable.MEFcodigo = LobjEntregableModelo.MEFcodigo;
        //    LobjEntregable.MNTnombre = LobjEntregableModelo.MNTnombre;
        //    LobjEntregable.MNTdescripcion = LobjEntregableModelo.MNTdescripcion;
        //    LobjEntregable.MNTfecha_Registro = Convert.ToDateTime(LobjEntregableModelo.MNTfecha_Registro);
        //    LobjEntregable.MNTnomenclatura = LobjEntregableModelo.MNTnomenclatura;
        //    LobjEntregable.MNTestado = LobjEntregableModelo.MNTestado;

        //    if (LobjEntregable.MNTcodigo == 0)
        //    {
        //        LstrMensajeRespuesta = PobjEntregable.mtdGuardarPrincipal(LobjEntregable);
        //        mtdRespuestaMensaje(LstrMensajeRespuesta);
        //    }
        //    else
        //    {
        //        LstrMensajeRespuesta = mtdModificar(LobjEntregable);
        //        mtdRespuestaMensaje(LstrMensajeRespuesta);

        //    }
        //    return Redirect("~/cnfMantenimiento/cnfClsEntregable/cnfFrmEntregableVista");
        //}

        //public string mtdModificar(cnfMNTpMetodologiaEntregable PobjEntregableModelo)
        //{
        //    string LstrMensajeRespuesta = "";
        //    LstrMensajeRespuesta = PobjEntregable.mtdModificar(PobjEntregableModelo);
        //    return LstrMensajeRespuesta;
        //}

        public void mtdRespuestaMensaje(string LstrMensajeRespuesta)
        {
            if (LstrMensajeRespuesta.Equals("Correcto"))
            {
                Session["GblnMensaje"] = true;
                Session["GstrMensajeRespuesta"] = "La Operación se Realizó Correctamente";
            }
            else
            {
                Session["GblnMensaje"] = true;
                Session["GstrMensajeRespuesta"] = "Ocurrió un Fallo en la Operación";
            }
        }

        //public ActionResult cnfFrmEntregableRelacionVista(int id = 0)
        //{
        //    try
        //    {
        //        if (ViewBag.GblnMensaje == null)
        //        {
        //            ViewBag.GblnMensaje = Convert.ToBoolean(Session["GblnMensaje"].ToString());
        //            ViewBag.GstrMensajeRespuesta = Convert.ToString(Session["GstrMensajeRespuesta"].ToString());
        //        }
        //    }
        //    catch
        //    {

        //    }
        //    ViewBag.GintCodigoEntregable = id;
        //    ViewBag.GobjListarEntregable = mtdCargarDatosSecundario(id);
        //    ViewBag.GobjListarEntregableRelacion = mtdCargarDatosSecundarioRelacion(id);
        //    Session["GblnMensaje"] = false;
        //    Session["GstrMensajeRespuesta"] = "";
        //    Session["GintMNTcodigo"] = id;
        //    return View();
        //}

        //public object mtdCargarDatosSecundario(int LintCodigo)
        //{
        //    return PobjEntregable.mtdCargarDatosSecundario(LintCodigo);
        //}

        //public object mtdCargarDatosSecundarioRelacion(int LintCodigo)
        //{
        //    return PobjEntregable.mtdCargarDatosSecundarioRelacion(LintCodigo);
        //}

        //public ActionResult mtdGuardarSecundario(string[] MNTcodigo_Relacion = null, int MNTcodigo = 0)
        //{
        //    string LstrMensajeRespuesta = "";

cnfPrySGCS/cnfPrySGCS/Areas/cnfProyecto/Views/cnfClsEntrega/View.cshtml
@{
    ViewBag.Title = "View";
    Layout = "~/Views/_ViewStart.cshtml";
}

<h2>View</h2>

cnfPrySGCS/cnfPrySGCS/Areas/cnfProyecto/Views/cnfClsEntrega/cnfFrmEntregaEvaluador.cshtml
@model cnfPrySGCS.Models.cnfEEMpEntregaEntregableMiembro
@{
    List<cnfPrySGCS.Models.cnfEEMpEntregaEntregableMiembro> GobjListarEntrega = ViewBag.ListarEntrega;
    bool LblnMensaje = false;
    try
    {
        LblnMensaje = ViewBag.GblnMensaje;
    }
    catch
    {

    }
}
@try
{
    if (LblnMensaje)
    {
        string LstrMensaje = ViewBag.GstrMensajeRespuesta;

        if (LstrMensaje.Equals("La Operación se Realizó Correctamente"))
        {
            <script>
                    alert('La Operación se Realizó Correctamente');
            </script>
        }
        else
        {
            <script>
                    alert('Ocurrió un Fallo en la Operación');
            </script>
        }
    }
}
catch
{

}

<div class="row">
    <div class="col-md-12">
        <div class="block-web">
            <div class="header">
                <div class="actions">
                    <a class="minimize" href="#">Evaluador<i class="fa fa-chevron-down"></i></a>
                </div>
            </div>
            <div class="porlets-content">
                <div class="adv-table editable-table ">
                    <div class="margin-top-10"></div>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="dataTables_length" id="editable-sample_length">
                            </div>
                        </div><div class="col-lg-12"><label>Buscar: <input class="txtBuscar form-control" aria-controls="editable-sample" data-table="order-table" type="search" placeholder="Buscar por Nombre..." /></label></div>
                    </div>
                    <table class="table table-striped table-hover table-bordered order-table" id="editable-sample">
                        <thead>
                            <tr>
                                <th>Codigo</th>
                                <th>Nombre</th>
                                <th>Cargo</th>
                                <th>Accion</th>



                            </tr>
                        </thead>
                        <tbody>
                            @*@try
                                {
                                    foreach (var LobjRegistro in GobjListarMetodologia)
                                    {
                                        <tr class="">
                                            <td>@LobjRegistro.MTDcodigo</td>
                                            <td>@LobjRegistro.MTDnombre</td>
                                            @try
                                            {
                                                string LstrFechaActual = Convert.ToDateTime(LobjRegistro.MTDfecha_Registro).ToString("d");
                                                <td>@LstrFechaActual</td>
                                            }
                                            catch
                                            {

                                            }
                                            <td>@LobjRegistro.MTDestado</td>
                                            <td><a class="btn btn-warning" href="~/cnfMantenimiento/cnfClsMetodologia/cnfFrmMetodologiaVista/@LobjRegistro.MTDcodigo">Modificar</a></td>
                                        </tr>
                                    }
                                }
                                catch
                                {

                                }*@
                        </tbody>
                    </table>
                </div>
            </div><!--/porlets-content-->
        </div><!--/block-web-->
    </div><!--/col-md-12-->
</div><!--/row-->

cnfPrySGCS/cnfPrySGCS/Areas/cnfProyecto/Views/cnfClsEntrega/cnfFrmEntregaResponsable.cshtml
<div class="row">
    <div class="col-md-12">
        <div class="block-web">
            <div class="header">
                <div class="actions">
                    <a class="minimize" href="#">Responsable<i class="fa fa-chevron-down"></i></a>
                </div>
            </div>
            <div class="porlets-content">
                <div class="adv-table editable-table ">
                    <div class="margin-top-10"></div>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="dataTables_length" id="editable-sample_length">
                            </div>
                        </div><div class="col-lg-12"><label>Buscar: <input class="txtBuscar form-control" aria-controls="editable-sample" data-table="order-table" type="search" placeholder="Buscar por Nombre..." /></label></div>
                    </div>
                    <table class="table table-striped table-hover table-bordered order-table" id="editable-sample">
                        <thead>
                            <tr>
                                <th>Codigo</th>
                                <th>Nombre</th>
                                <th>Cargo</th>
                                <th>Accion</th>
                            


                            </tr>
                        </thead>
                        <tbody>
                            @*@try
                                {
                                    foreach (var LobjRegistro in GobjListarMetodologia)
                                    {
                                        <tr class="">
                                            <td>@LobjRegistro.MTDcodigo</td>
                                            <td>@LobjRegistro.MTDnombre</td>
                                            @try
                                            {
                                                string LstrFechaActual = Convert.ToDateTime(LobjRegistro.MTDfecha_Registro).ToString("d");
                                                <td>@LstrFechaActual</td>
                                            }
                                            catch
                                            {

                                            }
                                            <td>@LobjRegistro.MTDestado</td>
                                            <td><a class="btn btn-warning" href="~/cnfMantenimiento/cnfClsMetodologia/cnfFrmMetodologiaVista/@LobjRegistro.MTDcodigo">Modificar</a></td>
                                        </tr>
                                    }
                                }
                                catch
                                {

                                }*@
                        </tbody>
                    </table>
                </div>
            </div><!--/porlets-content-->


        </div><!--/block-web-->
    </div><!--/col-md-12-->
</div><!--/row-->

cnfPrySGCS/cnfPrySGCS/Areas/cnfProyecto/Views/cnfClsEntrega/cnfFrmEntregaVista.cshtml
@model cnfPrySGCS.Models.cnfEMEpEntregableMiembroEntregable
@{
    List<cnfPrySGCS.Models.cnfEMEpEntregableMiembroEntregable> GobjListarEntrega = ViewBag.GobjListarEntrega;
 
    List<cnfPrySGCS.Models.cnfPRYpProyecto> GobjListarProyecto = ViewBag.GobjListarProyecto;
    List<cnfPrySGCS.Models.cnfMTDpMetodologia> GobjListarMetodologia = ViewBag.GobjListarMetodologia;
    List<cnfPrySGCS.Models.cnfMEFpMetodologiaFase> GobjListarFase = ViewBag.GobjListarGobjListarFase;

    bool LblnMensaje = false;
    try
    {
        LblnMensaje = ViewBag.GblnMensaje;
    }
    catch
    {

    }
}


<script type="text/javascript">
    function mtdSeleccion(LobjObjeto) {
        if ($(LobjObjeto).attr("name") == "PRYcodigo") {
            document.getElementById("frmCargarComboMetodologia").submit();
        }

        if ($(LobjObjeto).attr("name") == "btnGuardar") {

            document.getElementById("frmEntregable").submit();
        }
    }
</script>






@try
{
    if (LblnMensaje)
    {
        string LstrMensaje = ViewBag.GstrMensajeRespuesta;

        if (LstrMensaje.Equals("La Operación se Realizó Correctamente"))
        {
            <script>
                    alert('La Operación se Realizó Correctamente');
            </script>
        }
        else
        {
            <script>
                    alert('Ocurrió un Fallo en la Operación');
            </script>
        }
    }
}
catch
{

}
<script type="text/javascript">
(function(document) {
  'use strict';

  var LightTableFilter = (function(Arr) {

    var _input;

    function _onInputEvent(e) {
      _input = e.target;
      var tables = document.getElementsByClassName(_input.getAttribute('data-table'));
      Arr.forEach.call(tables, function(table) {
        Arr.forEach.call(table.tBodies, function(tbody) {
          Arr.forEach.call(tbody.rows, _filter);
        });
      });
    }

    function _filter(row) {
      var text = row.textContent.toLowerCase(), val = _input.value.toLowerCase();
      row.style.display = text.indexOf(val) === -1 ? 'none' : 'table-row';
    }

    return {
      init: function() {
        var inputs = document.getElementsByClassName('txtBuscar');
        Arr.forEach.call(inputs, function(input) {
          input.oninput = _onInputEvent;
        });
      }
    };
  })(Array.prototype);

  document.addEventListener('readystatechange', function() {
    if (document.readyState === 'complete') {
      LightTableFilter.init();
    }
  });

})(document);
</script>
<div class="row">
    <div class="col-md-12">
        <div class="block-web">
            <div class="header">
                <div class="actions"> <a class="minimize" href="~/Content/ultimo_admin/admin/#"><i class="fa fa-chevron-down"></i></a></div>
                <a href="~/cnfClsEntrega/cnfFrmEntregaVista"><h3 class="content-header">ENTREGA</h3></a>
            </div>
            <div class="porlets-content">
                @using (Html.BeginForm("mtdGuardar", "cnfClsEntrega", FormMethod.Post, new { id = "FrmEntrega", @name = "FrmEntrega", @class = "form-horizontal row-border" }))
                {
              

                    <div class="form-group">
                        <label name="lblCodigo" class="col-sm-3 control-label">Codigo</label>
                        <div class="col-sm-9">

                            @Html.TextBoxFor( x => x.EMEcodigo, new { @class = "form-control", disabled = true })
                        </div>
                    </div><!--/form-group-->


                    <div class="form-group">
                        <label name="lblFechaEntrega" class="col-sm-3 control-label">Fecha Registro</label>
                        <div class="col-sm-9">
                            @Html.TextBoxFor(model => model.EMEfecha_Registro, new { @class = "form-control", @required = "true", @pattern = "[A-Za-z ]+" })
                        </div>
                    </div><!--/form-group-->


                    <div class="form-group">
                        <label name="lblProyecto" class="col-sm-3 control-label">Proyecto</label>
                        <div class="col-sm-9">
                            <select class="form-control" id="source" name="PRYcodigo">
                                @foreach (var LobjRegistro in GobjListarProyecto)
                                {
                                    if (Model.PRYcodigo == LobjRegistro.PRYcodigo)
                                    {
                                        <option value="@LobjRegistro.PRYcodigo" selected>@LobjRegistro.PRYnombre</option>
                                    }
                                    else
                                    {
                                        <option value="@LobjRegistro.PRYcodigo">@LobjRegistro.PRYnombre</option>
                                    }
                                }
                            </select>
                        </div>
                    </div><!--/form-group-->

                 





                    <div class="form-group">
                        <label name="lblEstado" class="col-sm-3 control-label">Fases</label>
                        <div class="col-sm-9">
                            <select class="form-control" id="source" name="MTDestado">

                                <optgroup label="Fases">
                                    <option value="Activo">Activo</option>
                                    <option value="Inactivo">Inactivo</option>
                                </optgroup>


                            </select>
                        </div><!--/col-sm-9-->
                    </div><!--/form-group-->

                    <div class="form-group">
                        <label name="lblEstado" class="col-sm-3 control-label">Elemento de la Configuracion</label>
                        <div class="col-sm-9">
                            <select class="form-control" id="source" name="MTDestado">
                                @*@try
                                    {
                                        if (Model.MTDestado.Equals(""))
                                        {*@
                                <optgroup label="Elemento de...">
                                    <option value="Activo">Activo</option>
                                    <option value="Inactivo">Inactivo</option>
                                </optgroup>


                            </select>
                        </div><!--/col-sm-9-->
                    </div><!--/form-group-->

                    <div class="text-right">
                        <button type="reset" class="btn btn-success">Responsable</button>
                    </div>
                    <div class="text-right">
                        <label>             </label>
                    </div>
                    <div class="text-right">
                        <button type="reset" class="btn btn-success">Evaluador</button>
                    </div>


                    <div class="form-group">
                        <label name="lblFechaRegistro" class="col-sm-3 control-label">Registrar</label>
                        <div class="col-sm-9">
                            @try
                            {
                                DateTime LdttFechaActual = DateTime.Now;
                                string LstrFechaActual = LdttFechaActual.ToString("d");
                                <input type="text" class="form-control" disabled="" name="EMEfecha_Registro" value="@LstrFechaActual" />
                                <input type="hidden" class="form-control" name="EMEfecha_Registro" value="@LstrFechaActual" />
                            }
                            catch
                            {

                            }
                        </div>
                    </div><!--/form-group-->

                    <div class="text-right">
                        <button type="submit" class="btn btn-success">Guardar</button>
                    </div>

                }
                <div class="row">
                    <div class="col-md-12">
                        <div class="block-web">
                            <div class="header">
                                <div class="actions">
                                    <a class="minimize" href="#"><i class="fa fa-chevron-down"></i></a>
                                </div>
                            </div>
                            <div class="porlets-content">
                                <div class="adv-table editable-table ">
                                    <div class="margin-top-10"></div>
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="dataTables_length" id="editable-sample_length">
                                            </div>
                                        </div><div class="col-lg-12"><label>Buscar: <input class="txtBuscar form-control" aria-controls="editable-sample" data-table="order-table" type="search" placeholder="Buscar por Nombre..." /></label></div>
                                    </div>
                                    <table class="table table-striped table-hover table-bordered order-table" id="editable-sample">
                                        <thead>
                                            <tr>
                                                <th>Codigo</th>
                                                <th>Elemento Configuracion</th>
                                                <th>Responsable</th>
                                                <th>Evaluador</th>
                                                <th>Proyecto</th>
                                                <th>MetodologiaEntregable</th>
                                                <th>Fecha Registro</th>
                                                <th>Fecha Entrega</th>

                                               
                                                <th>Accion</th>


                                            </tr>
                                        </thead>
                                        <tbody>
                                            @try
                                                {
                                                    foreach (var LobjRegistro in GobjListarEntrega)
                                                    {
                                                        <tr class="">
                                                            <td>@LobjRegistro.EMEcodigo</td>
                                                            <td>@LobjRegistro.PECcodigo</td>
                                                            <td>@LobjRegistro.PMIcodigo_Responsable</td>
                                                            <td>@LobjRegistro.PMIcodigo_Evaluador</td>
                                                            <td>@LobjRegistro.PRYcodigo</td>
                                                            <td>@LobjRegistro.MNTcodigo></td>
                                                            <td>@LobjRegistro.EMEfecha_Registro</td>
                                                            <td>@LobjRegistro.EMEfecha_Entrega</td>
                                                            <td><a class="btn btn-warning" href="~/cnfProyecto/cnfClsEntrega/cnfFrmEntregaVista/@LobjRegistro.EMEcodigo">Modificar</a></td>
                                                        </tr>
                                                    }
                                                }
                                                catch
                                                {

                                                }
                                        </tbody>
                                    </table>
                                </div>
                            </div><!--/porlets-content-->
                        </div><!--/block-web-->
                    </div><!--/col-md-12-->
                </div><!--/row-->
            </div>
        </div>
    </div>

</div>
    <script type="text/javascript">
        function mtdSeleccion(LobjObjeto) {
            if ($(LobjObjeto).attr("name") == "PRYcodigo") {
                document.getElementById("frmCargarComboProyecto").submit();
            }
            if ($(LobjObjeto).attr("name") == "btnGuardar") {

                document.getElementById("frmEntregable").submit();
            }
        }
</script>